name: oruphones_app
description: OruPhones Flutter Internship Assignment
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  stacked: ^3.4.1
  stacked_services: ^1.3.0

  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_auth: ^4.15.3

  # Storage & Caching
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2

  # Network
  dio: ^5.4.0
  internet_connection_checker: ^1.0.0+1

  # UI Components
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  shimmer: ^3.0.0
  infinite_scroll_pagination: ^4.0.0

  # Utils
  intl: ^0.19.0
  logger: ^2.0.2+1
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: 2.4.6
  stacked_generator: 1.5.1
  json_serializable: 6.7.1
  
  # Linting
  flutter_lints: 2.0.0

flutter:
  uses-material-design: true

  # Add assets and fonts configuration as needed
