name: oruphones_app
description: OruPhones Flutter Internship Assignment
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.6.0
  cupertino_icons: ^1.0.2
  stacked: ^3.4.4
  stacked_services: ^1.6.0
  dio: ^5.3.2  # For API calls
  shared_preferences: ^2.2.0  # For persisting auth state
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  permission_handler: ^11.1.0  # For handling permissions
  google_fonts: ^6.1.0  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6  # For code generation
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/
    - assets/images/logo.png
    - assets/images/user.png
    - assets/icons/how_to_buy.png
    - assets/icons/how_to_sell.png
    - assets/icons/faqs.png
    - assets/icons/about_us.png
    - assets/icons/privacy_policy.png
    - assets/icons/return_policy.png
    - assets/icons/oru_guide.png
    - assets/icons/logout.png
    - assets/icons/menu.png
    - assets/icons/location.png
    - assets/icons/search.png
    - assets/icons/mic.png
    - assets/icons/new.png
    - assets/banners/banner1.png
    - assets/banners/banner2.png
    - assets/banners/banner3.png
    - assets/banners/banner4.png
    - assets/banners/banner5.png
    - assets/banners/  # Add this line
